### ISSUE TITLE
[TASK] Mention pwa_manfiest in README

### ISSUE THREAD

**Issue by lukaszuznanski** [TYPO3-Initiatives/headless#68]

**Comment by MarinaC** [comment]
Hi! How to use actually this extension? Readme unfortunately do not gives the full information how it is possible to get the JSON instance from the TYPO3-Backend-Form? Which steps are needed to do?
Could you please provide the steps description, where and what should I access to start further development or usage of headless extension.

Thank you in advance!

**Comment by lukaszuznanski** [comment]
Hi,

are you talking about headless? If so, to get JSON instance from TYPO3, all you need is to include typoscript template, and disable other rendering templates like fluid styled content, and that's all what you really need. It's mentioned in readme, but I'm working on better documentation atm. Please message me on slack if you have any problems with setup.

**Comment by MarinaC** [comment]
Dear Lukasz,

I would like to write with you better in Slack to describe my problem,
which I have and how it is better to solve with headless extension.
But when I click on the link in GIT it shows me that I should be registered
for accessing the Slack-group.
Could you please invite me into the Slack-group?

Thank you and best regards,
Marina

Am Di., 25. Feb. 2020 um 13:13 Uhr schrieb Łukasz Uznański <
notifications@github.com>:

**Comment by lukaszuznanski** [comment]
Hi,

https://typo3.org/community/meet/how-to-use-slack-in-the-typo3-community join this Slack, and then go to #initiative-pwa or write DM to me :).

**Comment by MarinaC** [comment]
Dear Lukasz,

Could you please help me with my extension?

I want to use *headless* to create the JSON-file (JSON-output) first for
one article in the news overview and then append it to the common JSON-file
with articles.
Instead of it I get the whole content of the article page as JSON-output
with *headless*. Like all that unneeded configurations as colour, font
size, header name of the page etc.

I use Typo3 version 9.5.13. I the attachment you would find my extension,
which should be used to create articles (like news & events) and save them
into the JSON file (which you also find in attachment).

Thank you and many greetings,
Marina

Am Mi., 26. Feb. 2020 um 11:01 Uhr schrieb Łukasz Uznański <
notifications@github.com>:

**Comment by lukaszuznanski** [comment]
Hi,

unfortunately, I don't have your attachments, because you commented via email, and you can't upload attachments here. Please reach me via Slack and then I can help you.
